services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: nms
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    environment:
      NMS_DB_URL: jdbc:postgresql://db:5432/nms
      NMS_DB_USERNAME: postgres
      NMS_DB_PASSWORD: postgres
      NMS_ADMIN_USERNAME: admin
      NMS_ADMIN_PASSWORD: admin
      NMS_ADMIN_EMAIL: admin@nms.com
    depends_on:
      - db
    ports:
      - "8080:8080"
  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    depends_on:
      - backend
    ports:
      - "443:443"
volumes:
  db-data:
