spring.datasource:
  url: jdbc:postgresql://localhost:5432/nms
  username: postgres
  password: postgres

spring.jpa:
  hibernate.ddl-auto: update
  show-sql: true
  properties:
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect

nms.security:
  jwt:
    token-expiration-millis: 604800000 # 1 week
    token-secret: 11c023y2012nm19c071mycy0m80cm49809ib6v345v4
  admin:
    username: admin
    password: admin
    email: admin@nms.com
